# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm_token
    steps:
    - uses: actions/checkout@v3

    - name: cache node_modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'yarn'
    - name: setup yarn
      run: |
        npm install yarn -g 

    - name: install
      run: |
        yarn install 
    - name: build
      run: |
        yarn build 
    - name: upload build
      uses: actions/upload-artifact@v3
      with:
        name: build
        # version number is set in package.json so need to include that
        path: |
          package.json
  release_npm:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: setup git
          run: |
            git config --global user.name 'leonardoFu'
            git config --global user.email 'leonardoFu@users.noreply.github.com'
        - name: cache node_modules
          uses: actions/cache@v3
          env:
            cache-name: cache-node-modules
          with:
            path: ~/.npm
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-

        - name: use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 14.x
            cache: 'yarn'

        - name: download build
          uses: actions/download-artifact@v3
          with:
            name: build
        - name: npm version 
          run: |
            npm version patch
        - name: setup npm
          run: |
            ./setup_npm.sh
          env:
            CI: true
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        - name: publish
          run: |
            npm publish
        - name: push back
          run: |
            git add .
            git commit -am "Version auto published"
            git push